"""
Train and export YOLOv8-nano-seg for tile detection (Stage 1).

Full pipeline:
    1. Generate tile STLs     : python scripts/batch_generate_stls.py --out tiles/ --n 500
    2. Render training images : blender --background --python scripts/render_tiles.py -- ...
    3. THIS SCRIPT            : python scripts/train_yolov8.py
    4. Export CoreML/TFLite   : yolo export model=... format=coreml int8=True
    5. Deploy                 : python scripts/deploy_models.py

Prerequisites:
    pip install ultralytics          (installs yolov8 CLI + Python API)
    Blender 3.6+                     (for render_tiles.py step)
    dataset/tile_detect.yaml         (generated by render_tiles.py)

Target accuracy: 95% recall @ IOU 0.5 on held-out real garment photos.
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument('--data',    type=Path, default=Path('dataset/tile_detect.yaml'),
                    help='YOLO dataset YAML from render_tiles.py (default: dataset/tile_detect.yaml)')
    ap.add_argument('--epochs',  type=int,  default=100)
    ap.add_argument('--imgsz',   type=int,  default=640)
    ap.add_argument('--batch',   type=int,  default=16,
                    help='batch size (reduce if OOM; 16 works on 8 GB VRAM)')
    ap.add_argument('--device',  type=str,  default='',
                    help='device: "" (auto), "cpu", "0" (first GPU), "mps" (Apple Silicon)')
    ap.add_argument('--model',   type=str,  default='yolov8n-seg.pt',
                    help='base model (yolov8n-seg.pt=nano, yolov8s-seg.pt=small)')
    ap.add_argument('--out',     type=Path, default=Path('models'),
                    help='output directory for exported models')
    ap.add_argument('--export',  action='store_true',
                    help='export best.pt to CoreML + TFLite after training')
    ap.add_argument('--resume',  action='store_true',
                    help='resume a previous training run')
    args = ap.parse_args()

    try:
        from ultralytics import YOLO
    except ImportError:
        print('ultralytics not installed. Run: pip install ultralytics', file=sys.stderr)
        sys.exit(1)

    if not args.data.exists():
        print(f'ERROR: dataset YAML not found: {args.data}', file=sys.stderr)
        print('Run render_tiles.py first to generate training data.', file=sys.stderr)
        sys.exit(1)

    # Training
    model = YOLO(args.model)
    train_kwargs = dict(
        data=str(args.data),
        epochs=args.epochs,
        imgsz=args.imgsz,
        batch=args.batch,
        task='segment',
        verbose=True,
        save=True,
        val=True,
        plots=True,
        # Augmentation (supplement Blender augmentations)
        fliplr=0.5,
        flipud=0.0,     # tiles have no up/down convention — leave as rendered
        degrees=0.0,    # already rotated in Blender
        perspective=0.0,
        mosaic=0.5,
        mixup=0.1,
    )
    if args.device:
        train_kwargs['device'] = args.device
    if args.resume:
        train_kwargs['resume'] = True

    print(f'Training YOLOv8-nano-seg on {args.data} ...')
    results = model.train(**train_kwargs)

    best_pt = Path(results.save_dir) / 'weights' / 'best.pt'
    print(f'\nTraining complete. Best model: {best_pt}')
    print(f'Metrics: mAP50={results.results_dict.get("metrics/mAP50(B)", "n/a")}')

    # Copy best.pt to models/
    args.out.mkdir(parents=True, exist_ok=True)
    import shutil
    dest = args.out / 'tile_detector.pt'
    shutil.copy2(best_pt, dest)
    print(f'Copied: {dest}')

    if args.export:
        print('\nExporting to CoreML ...')
        model_best = YOLO(str(best_pt))
        # CoreML (iOS)
        model_best.export(format='coreml', imgsz=args.imgsz, int8=True,
                          nms=True)
        # TFLite INT8 (Android)
        model_best.export(format='tflite', imgsz=args.imgsz, int8=True)

        # Copy exports
        for ext, dst_name in [('.mlpackage', 'tile_detector.mlpackage'),
                               ('_int8.tflite', 'tile_detector.tflite')]:
            src = best_pt.parent / f'best{ext}'
            if src.exists():
                shutil.copy2(src, args.out / dst_name)
                print(f'Copied: {args.out / dst_name}')
            else:
                print(f'SKIP: {src} not found (check Ultralytics export output)')

        print('\nDeploy with: python scripts/deploy_models.py')
    else:
        print('\nTo export CoreML + TFLite, re-run with --export flag.')
        print(f'Or manually: yolo export model={best_pt} format=coreml int8=True')

    print('\nValidation on real photos:')
    print(f'  yolo val model={best_pt} data=real_test/tile_real.yaml')


if __name__ == '__main__':
    main()
